### PR TITLE
Revert "Update(Dockerfile): Use ubi9 images that contains required gl…

### PR DESCRIPTION
**Pull request by rkubis**
…ibc version by gqlgen (#135)"

This reverts commit 6595e84e5c8f342321f97d8cfae63e75997020d3.

## Description
We can go back to ubi8 images that are sufficient for image building.

## How Has This Been Tested?
```
docker build -t model-registry .
```

## Merge criteria:
- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
To me, this is a welcome revert, also to account for advisories
image

We can concentrate on updating to an *alternative stable image only if strictly required later

**Comment by rkubis** [comment]
New `ubi8/go-toolset:1.20` and `ubi8/ubi-minimal:8.9` are available now.

**Comment by tarilabs** [comment]
> New `ubi8/go-toolset:1.20` and `ubi8/ubi-minimal:8.9` are available now.

I'd vote to merge this PR as-is, see back ubi8 on quay, check that works with colima/rosetta/qemu, and then take the bump to ubi8.9 etc in subsequent PR.
What do you think?

**Comment by rkubis** [comment]
> I'd vote to merge this PR as-is, see back ubi8 on quay, check that works with colima/rosetta/qemu, and then take the bump to ubi8.9 etc in subsequent PR.
What do you think?

Yes, it is my idea too.

**Pull request merged**
