### PR TITLE
doc: Document MR Logical Model

### PR DESCRIPTION
**Pull request by tarilabs**
## Description
produce a documentation of the logical model for MR entities and example to use metadata (`customProperties`) to support UI request to store for S3 case Endpoint, Bucket, in addition to Path which is already existing, but without changing the current MR logical model

@lucferbux this is MD materialization of the google doc already discussed.

## How Has This Been Tested?
n/a

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [n/a] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [n/a] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by lampajr — COMMENTED** [review]
I would also add a link to this new document from the main README.md for visibility, wdyt?

**Comment by tarilabs** [comment]
> I would also add a link to this new document from the main README.md for visibility, wdyt?

Done with d40fbe0

**Review by lampajr — APPROVED** [review]
Thanks @tarilabs, lgtm!

**Comment by tarilabs** [comment]
merging without openshift-ci given it's only Doc files, approvals (https://github.com/opendatahub-io/model-registry/pull/301#pullrequestreview-1879871149) and no vetos.

**Pull request merged**
