### PR TITLE
Fix golangci-lint local install instructions

### PR DESCRIPTION
**Pull request by lampajr**
## Description
As the `golangci-lint` [documentation](https://golangci-lint.run/usage/install/) suggests I would use `curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2` instead of `go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest`.

Their documentation explicitly says: "Note: such go install/go get installation aren't guaranteed to work. We recommend using binary installation."

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by lampajr** [comment]
Furthermore using the previous suggested command (`go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest`) I ran into:
```
# github.com/sashamelentyev/usestdlibvars/pkg/analyzer/internal/mapping
../../go/pkg/mod/github.com/sashamelentyev/usestdlibvars@v1.24.0/pkg/analyzer/internal/mapping/mapping.go:164:7: undefined: time.DateTime
../../go/pkg/mod/github.com/sashamelentyev/usestdlibvars@v1.24.0/pkg/analyzer/internal/mapping/mapping.go:165:7: undefined: time.DateOnly
../../go/pkg/mod/github.com/sashamelentyev/usestdlibvars@v1.24.0/pkg/analyzer/internal/mapping/mapping.go:166:7: undefined: time.TimeOnly
note: module requires Go 1.20
```

Which is not what we want as we have go >= 1.19 set in the go.mod and with this error the installation keeps failing.

**Review by tarilabs — APPROVED** [review]

**Review by antisaling — APPROVED** [review]
Nit: I'd say "Fix golangci-lint local install instructions" in the commit message just to be clear what this change is about (similar to what you did on the PR subject).

Otherwise, this LGTM :)

**Comment by lampajr** [comment]
> Nit: I'd say "Fix golangci-lint local install instructions" in the commit message just to be clear what this change is about (similar to what you did on the PR subject).
> 
> Otherwise, this LGTM :)

Updated, thx for the suggestion @isinyaaa !

**Comment by dhirajsb** [comment]
@lampajr good catch. I had upgraded my local go version, and that's why it was working for me. But we do want to keep things compatible with 1.19, if we can. The go convention is to support the last 3 go releases, and the latest is 1.21 right now. Looks like `go install golangci-lint@latest` breaks that.

**Review by dhirajsb — APPROVED** [review]
lgtm

**Comment by dhirajsb** [comment]
@lampajr if you are done you want to rebase and merge this in yourself? Get it in now so you don't have to rebase for other PRs. :smiley:

**Comment by lampajr** [comment]
> @lampajr if you are done you want to rebase and merge this in yourself? Get it in now so you don't have to rebase for other PRs. 😃

Sorry missed previous approval hehe, merged now :heavy_check_mark:

**Pull request merged**
