### PR TITLE
Creating OWNERS file needed for openshift-ci

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
Creating OWNERS file needed for openshift-ci. Including Neha Chopra (nehachopra27) in the OWNERS file as Neha will be added to the team as a contributor to model-registry.

### CODE REVIEW

**Comment by tonyxrmdavidson** [comment]
DRAFT
Will be merged once tonyxrmdavidson and nehachopra27 are added as members of openshift org

**Comment by tarilabs** [comment]
marked as draft per https://github.com/opendatahub-io/model-registry/pull/302#issuecomment-1941316463

**Review by lampajr — APPROVED** [review]

**Review by tarilabs — APPROVED** [review]

**Comment by tarilabs** [comment]
we will need to re-create this file eventually when re-forking from KF

**Pull request merged**
