### PR TITLE
Metadata mapping OpenAPI/gRPC for Bool and Struct

### LINKED ISSUE #83: Metadata mapping OpenAPI/gRPC for Bool and Struct
**Is your feature request related to a problem? Please describe.**
Extend coverage of Metadata mapping from OpenAPI layer for Bool and Struct value types.

**Describe the solution you'd like**
Acceptance criteria:
- Core Mapper to support for Bool and Struct value types
- Covered in unit tests via marshall+unmarshall

**Describe alternatives you've considered**
n/a

**Additional context**
nothing

### PR DESCRIPTION
**Pull request by tarilabs**
Resolves #83 

## Description
Satisfies acceptance criteria of #83 

## How Has This Been Tested?
```
go test ./internal/...
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by lampajr — DISMISSED** [review]
lgtm

**Comment by lampajr** [comment]
@tarilabs I think you should run `go mod tidy` otherwise there are some uncommmitted changes

**Review by lampajr — APPROVED** [review]

**Review by dhirajsb — APPROVED** [review]
/lgtm

**Comment by tarilabs** [comment]
two approvals, no vetos, proceeding to merge for the benefits of other open PRs.

**Pull request merged**
