### PR TITLE
add pre-commit hooks

### LINKED ISSUE #277: Add auto-formatters
Auto-formatters can reduce development overhead significantly, so we should adopt them for the languages used in the project.

### PR DESCRIPTION
**Pull request by antisaling**
Closes: #277

Add pre-commit hooks to fix common formatting issues.

## Description

users who have the `pre-commit` tool installed will have the tool perform actions before every commit, ensuring minimal standards in the code-base, while hopefully not adding much overhead.

Most fixes are harmless, and I've performed a `pre-commit run --all-files` on the same commit in which the tool was added, so that further runs would only show new issues.

The Python linter is more aggressive than the others, but can also be removed.

It's important to note that `pre-commit` is not prescriptive, and it's easy to disable the tool using the `--no-verify` flag on your commits.

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by tarilabs** [comment]
I'm not entirely sure why a blank line in GHA workflow file is a formatting "issue" 🤔 , as you will find many examples on GitHub docs provided that way.

Besides that, you might want consider excluding some files from this scope, to make the build passing again.

**Comment by antisaling** [comment]
codecov seems to be failing for no apparent reason, I'll wait a while before re-triggering.

**Review by tarilabs — APPROVED** [review]
As previously approved in https://github.com/opendatahub-io/model-registry/pull/285#issuecomment-1920666695 but I don't believe empty space in YAML for GHA is technically "an issue", given most examples from GH docs are designed that way. Given this PR is a prerequisite for other more priority work, I'd merge this asap.

**Review by lampajr — APPROVED** [review]
I agree that new lines in GHA yaml shouldn't be an issue, maybe just some config that can be tweaked (?)

btw it looks good to me!

**Comment by antisaling** [comment]
Those are the only docs that I found on the `yamlfmt` plugin: https://github.com/google/yamlfmt/blob/b9587d5d7418ff87de0fa3e5377dd622dd5844d8/docs/pre-commit.md?plain=1

though it looks like this is one of the best, it's not perfect, if you have suggestion I'll be happy to hear them :). In either case, I'll assume this is ready to be merged.

**Pull request merged**
