### PR TITLE
feat: add kustomize manifests for kubeflow, fixes RHOAIENG-1947

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Add kustomize manifests for kubeflow
Based on ml-metadata manifests for mlmd in kubeflow pipelines.
Fixes [RHOAIENG-1947](https://issues.redhat.com//browse/RHOAIENG-1947)

## How Has This Been Tested?

WIP

## Merge criteria:

- [X] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dhirajsb** [comment]
PR is in draft, do NOT merge!

**Comment by dhirajsb** [comment]
@tarilabs can you approve it so that we can merge it into upstream kubeflow?

**Review by tarilabs — APPROVED** [review]
> @tarilabs can you approve it so that we can merge it into upstream kubeflow?

absolutely, thanks for these @dhirajsb, I understand these are manifests to use model-registry in place of Operator (say upstream KF) eventually it will be meaningful to be put under tests but given the urgency this /lgtm and we can work on placing under tests in subsequent PRs.

**Comment by tarilabs** [comment]
@dhirajsb also for the future don't hesitate to use @opendatahub-io/model-registry-maintainers tags in Review box when needed urgent action we can rely on who's on in the timezone :) hth 👍

**Pull request merged**
