### PR TITLE
Improvements to Makefile

### PR DESCRIPTION
**Pull request by sabre1041**
## Description
Improvements to Makefile to enable simplified building across multiple versions of `make`

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
can someone on a linux box try this one out to confirm working on their end (non-Mac users) please?

thank you so much @sabre1041 ! 🚀

**Comment by rareddy** [comment]
what needs to be checked? I have linux box. I tried `make build`, I do not think below is anything to do with @sabre1041 PR but see below

```
$make build
/home/rareddy/development/model-registry/bin/openapi-generator-cli validate -i api/openapi/model-registry.yaml
Validating spec (api/openapi/model-registry.yaml)
No validation issues detected.
INFO api/openapi/model-registry.yaml is not staged or modified, will not re-generate server
/home/rareddy/development/model-registry/bin/goverter gen github.com/opendatahub-io/model-registry/internal/converter/
error parsing 'goverter:default' at
    /home/rareddy/development/model-registry/internal/converter/openapi_converter.go:68:2
    func (github.com/opendatahub-io/model-registry/internal/converter.OpenAPIConverter).OverrideNotEditableForDocArtifact(source github.com/opendatahub-io/model-registry/internal/converter.OpenapiUpdateWrapper[github.com/opendatahub-io/model-registry/pkg/openapi.DocArtifact]) (github.com/opendatahub-io/model-registry/pkg/openapi.DocArtifact, error)

unknown setting: default
make: *** [Makefile:62: internal/converter/generated/converter.go] Error 1
```

**Comment by tarilabs** [comment]
Tested with:

```
GNU Make 4.4.1
Built for aarch64-apple-darwin22.3.0
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by tarilabs** [comment]
Also tested with:

```
GNU Make 4.4.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

on:

```
Linux fedora 6.6.14-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jan 26 20:12:16 UTC 2024 x86_64 GNU/Linux
```

Screenshot from 2024-02-17 11-02-15

/lgtm

**Pull request merged**
