### PR TITLE
Add go core library documentation

### LINKED ISSUE #147: Add documentation for the Model Registry Go core library
Add documentation for the model registry Go core library at https://github.com/opendatahub-io/model-registry/blob/1a7a4138d88267602b4901946e0956b5f1a09d1b/README.md#model-registry-library.

We could create a separate README.md under `/pkg` folder and reference it from the root README.
This section should include:
- Library installation
- Library usage
- Simple usage example (with mlmd setup)

### PR DESCRIPTION
**Pull request by lampajr**
Fixes https://github.com/opendatahub-io/model-registry/issues/147

## Description

* Added go doc for all `ModelRegistryService` methods, these infos will be automatically published on [pkg.go.dev](https://pkg.go.dev/github.com/opendatahub-io/model-registry).

* Added simple `getting started guide` for the library installation and usage.

## How Has This Been Tested?

```bash
make test
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by tarilabs** [comment]
I believe we were considering "the pattern" of `parentResourceId`... what's the group view on this? 🤔

**Comment by lampajr** [comment]
> I believe we were considering "the pattern" of `parentResourceId`... what's the group view on this? 🤔 

Yeah but from the documentation point of view I think it is better to explicitly set parent, otherwise user might find hard to identify which is the correct parent to use.

On the other hand those are just a local variable names, so I can revert using the `parentResourceId` in the code and keep all infos in the comment only.

**Review by tarilabs — DISMISSED** [review]

**Comment by lampajr** [comment]
>[force-pushed](https://github.com/opendatahub-io/model-registry/compare/7cef01b3dadde9fa863a7f3515927cf33dcf7af9..a14a839dec95e2cb050f3309fef02fd9e6314f51) the lampajr_20231127_gh147_go_doc branch from [7cef01b ](https://github.com/opendatahub-io/model-registry/commit/7cef01b3dadde9fa863a7f3515927cf33dcf7af9)to [a14a839](https://github.com/opendatahub-io/model-registry/commit/a14a839dec95e2cb050f3309fef02fd9e6314f51)

Fixed conflict from `main` branch

**Comment by lampajr** [comment]
> Fixed conflict from `main` branch

Rebased from `main` and fixed conflict again :)

**Review by tarilabs — APPROVED** [review]

**Pull request merged**
